const categoryQuestions = {
  1: 'Разминка',
  2: 'Воробьиные',
  3: 'Лесные птицы',
  4: 'Певчие птицы',
  5: 'Хищные птицы',
  6: 'Морские птицы',
}
// { en: 'Swift:', ru: "стриж", answer: null, description: null, photo: null,song: null},
// { en: 'Blackbird:', ru: "дрозд", answer: null, description: null, photo: null,song: null},
// { en: 'Crane:', ru: "журавль", answer: null, description: null, photo: null,song: null},
// { en: 'Ostrich:', ru: "страус", answer: null, description: null, photo: null,song: null},
// { en: 'Hummingbird:', ru: "колибри", answer: null, description: null, photo: null,song: null},
// { en: 'Stork:', ru: "аист", answer: null, description: null, photo: null,song: null},
const list = {
  1: [
    { en: 'Dove', ru: "голубь", answer: null, description: null, photo: null,song: null},
    { en: 'Raven', ru: "ворон", answer: null, description: null, photo: null,song: null},
    { en: 'Peacock', ru: "павлин", answer: null, description: null, photo: null,song: null},
    { en: 'Magpie', ru: "сорока", answer: null, description: null, photo: null,song: null},
    { en: 'Crow', ru: "ворона", answer: null, description: null, photo: null,song: null},
    { en: 'Swallow', ru: "ласточка", answer: null, description: null, photo: null,song: null},
  ],
  2: [
    { en: 'Sparrow', ru: "воробей", answer: null, description: null, photo: null,song: null},
    { en: 'Bullfinch', ru: "снегирь", answer: null, description: null, photo: null,song: null},
    { en: 'Titmouse', ru: "синица", answer: null, description: null, photo: null,song: null},
    { en: 'Nightingale', ru: "соловей", answer: null, description: null, photo: null,song: null},
    { en: 'Goldcrest', ru: "королек", answer: null, description: null, photo: null,song: null},
    { en: 'Canary', ru: "канарейка", answer: null, description: null, photo: null,song: null},
  ],
  3: [
    { en: 'Cuckoo', ru: "кукушка", answer: null, description: null, photo: null,song: null},
    { en: 'Woodpecker', ru: "дятел", answer: null, description: null, photo: null,song: null},
    { en: 'Owl', ru: "сова", answer: null, description: null, photo: null,song: null},
    { en: 'Partridge', ru: "куропатка", answer: null, description: null, photo: null,song: null},
    { en: 'Heath-cock', ru: "тетерев", answer: null, description: null, photo: null,song: null},
    { en: 'Pheasant', ru: "фазан", answer: null, description: null, photo: null,song: null},
  ],
  4: [
    { en: 'Parrot', ru: "попугай", answer: null, description: null, photo: null,song: null},
    { en: 'Lark', ru: "жаворонок", answer: null, description: null, photo: null,song: null},
    { en: 'Oriole', ru: "иволга", answer: null, description: null, photo: null,song: null},
    { en: 'Chaffinch', ru: "зяблик", answer: null, description: null, photo: null,song: null},
    { en: 'Canary', ru: "канарейка", answer: null, description: null, photo: null,song: null},
    { en: 'Nightingale', ru: "соловей", answer: null, description: null, photo: null,song: null},

  ],
  5: [
    { en: 'Hawk', ru: "ястреб", answer: null, description: null, photo: null,song: null},
    { en: 'Vulture', ru: "гриф", answer: null, description: null, photo: null,song: null},
    { en: 'Eagle', ru: "орел", answer: null, description: null, photo: null,song: null},
    { en: 'Falcon', ru: "сокол", answer: null, description: null, photo: null,song: null},
    { en: 'Kite', ru: "коршун", answer: null, description: null, photo: null,song: null},
    { en: 'Loon', ru: "гагара", answer: null, description: null, photo: null,song: null},
  ],
  6: [
    { en: 'Penguin', ru: "пингвин", answer: null, description: null, photo: null,song: null},
    { en: 'Swan', ru: "лебедь", answer: null, description: null, photo: null,song: null},
    { en: 'Heron', ru: "цапля", answer: null, description: null, photo: null,song: null},
    { en: 'Flamingo', ru: "фламинго", answer: null, description: null, photo: null,song: null},
    { en: 'Cormorant', ru: "баклан", answer: null, description: null, photo: null,song: null},
    { en: 'Seagull', ru: "чайка", answer: null, description: null, photo: null,song: null},
  ],
  // Dove: "голубь",
  // Raven: "ворон",
  // Crow: "ворона",
  // Swift: "стриж",
  // Blackbird: "дрозд",
  // Chaffinch: "зяблик",
  // Crane: "журавль",
  // Ostrich: "страус",
  // Hummingbird: "колибри",
  // Stork: "аист",
}
export { list }
export { categoryQuestions }
