const categoryQuestions = {
  1: 'Разминка',
  2: 'Воробьиные',
  3: 'Лесные птицы',
  4: 'Певчие птицы',
  5: 'Хищные птицы',
  6: 'Морские птицы',
}
const list = {
  1: [
    { Dove: 'голубь', description: 'description', answer: null, photo: null },
    { Raven: 'ворон', description: 'description', answer: null, photo: null },
    {
      Peacock: 'павлин',
      description: 'description',
      answer: null,
      photo: null,
    },
    { Magpie: 'сорока', description: 'description', answer: null, photo: null },
    { Crow: 'ворона', description: 'description', answer: null, photo: null },
    {
      Swallow: 'ласточка',
      description: 'description',
      answer: null,
      photo: null,
    },
  ],
  2: [
    {
      Sparrow: 'воробей',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Bullfinch: 'снегирь',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Titmouse: 'синица',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Nightingale: 'соловей',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Goldcrest: 'королек',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Canary: 'канарейка',
      description: 'description',
      answer: null,
      photo: null,
    },
  ],
  3: [
    {
      Cuckoo: 'кукушка',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Woodpecker: 'дятел',
      description: 'description',
      answer: null,
      photo: null,
    },
    { Owl: 'сова', description: 'description', answer: null, photo: null },
    {
      Partridge: 'куропатка',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      'Heath-cock': 'тетерев',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Pheasant: 'фазан',
      description: 'description',
      answer: null,
      photo: null,
    },
  ],
  4: [
    {
      Parrot: 'попугай',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Lark: 'жаворонок',
      description: 'description',
      answer: null,
      photo: null,
    },
    { Oriole: 'иволга', description: 'description', answer: null, photo: null },
    {
      Chaffinch: 'зяблик',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Canary: 'канарейка',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Nightingale: 'соловей',
      description: 'description',
      answer: null,
      photo: null,
    },
  ],
  5: [
    { Hawk: 'ястреб', description: 'description', answer: null, photo: null },
    { Vulture: 'гриф', description: 'description', answer: null, photo: null },
    { Eagle: 'орел', description: 'description', answer: null, photo: null },
    { Falcon: 'сокол', description: 'description', answer: null, photo: null },
    { Kite: 'коршун', description: 'description', answer: null, photo: null },
    { Loon: 'гагара', description: 'description', answer: null, photo: null },
  ],
  6: [
    {
      Penguin: 'пингвин',
      description: 'description',
      answer: null,
      photo: null,
    },
    { Swan: 'лебедь', description: 'description', answer: null, photo: null },
    { Heron: 'цапля', description: 'description', answer: null, photo: null },
    {
      Flamingo: 'фламинго',
      description: 'description',
      answer: null,
      photo: null,
    },
    {
      Cormorant: 'баклан',
      description: 'description',
      answer: null,
      photo: null,
    },
    { Seagull: 'чайка', description: 'description', answer: null, photo: null },
  ],
  // Dove: "голубь",
  // Raven: "ворон",
  // Crow: "ворона",
  // Swift: "стриж",
  // Blackbird: "дрозд",
  // Chaffinch: "зяблик",
  // Crane: "журавль",
  // Ostrich: "страус",
  // Hummingbird: "колибри",
  // Stork: "аист",
}
export { list }
export { categoryQuestions }
