const categoryQuestions = {
    1:'Разминка',
    2:'Воробьиные',
    3:'Лесные птицы',
    4:'Певчие птицы',
    5:'Хищные птицы',
    6:'Морские птицы',
}
const list = {
    Dove: "голубь",
    Raven: "ворон",
    Woodpecker: "дятел",
    Titmouse: "синица",
    Crow: "ворона",
    Sparrow: "воробей",
    Cuckoo: "кукушка",
    Swallow: "ласточка",
    Oriole: "иволга",
    Lark: "жаворонок",
    Bullfinch: "снегирь",
    Swift: "стриж",
    Owl: "сова",
    Magpie: "сорока",
    Blackbird: "дрозд",
    Chaffinch: "зяблик",
    Partridge: "куропатка",
    "Heath-cock": "тетерев",
    Crane: "журавль",
    Nightingale: "соловей",
    Hawk: "ястреб",
    Canary: "канарейка",
    Ostrich: "страус",
    Penguin: "пингвин",
    Parrot: "попугай",
    Peacock: "павлин",
    Hummingbird: "колибри",
    Stork: "аист",
    Vulture: "гриф",
    Eagle: "орел",
    Swan: "лебедь",
    Falcon: "сокол",
    Pheasant: "фазан",
    Heron: "цапля",
    Flamingo: "фламинго",
    Seagull: "чайка",
    Kite: "коршун",
    Cormorant: "баклан",
    Loon: "гагара",
    Goldcrest: "королек",
}
export {list};
export {categoryQuestions}